[package]
name = "turtle_run"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
crossbeam = "0.8.4"
log = "0.4.22"
log4rs = "1.3.0"
rand = "0.8.5"
serde = { version = "1.0.214", features = ["derive"] }
serde_yaml = "0.9"